/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDiagnosticosRouteImport } from './routes/_authenticated/diagnosticos'
import { Route as AuthenticatedFormulariosRouteImport } from './routes/_authenticated/formularios'
import { Route as AuthenticatedMatrizRouteImport } from './routes/_authenticated/matriz'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedPlanoDeAcaoRouteImport } from './routes/_authenticated/plano-de-acao'
import { Route as AuthenticatedPlanoDeMarketingRouteImport } from './routes/_authenticated/plano-de-marketing'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as DTokenRouteImport } from './routes/d.$token'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes.$id'
import { Route as AuthenticatedDiagnosticosIdRouteImport } from './routes/_authenticated/diagnosticos.$id'
import { Route as AuthenticatedPlanoDeMarketingClientIdRouteImport } from './routes/_authenticated/plano-de-marketing.$clientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnosticosRoute =
  AuthenticatedDiagnosticosRouteImport.update({
    id: '/diagnosticos',
    path: '/diagnosticos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormulariosRoute =
  AuthenticatedFormulariosRouteImport.update({
    id: '/formularios',
    path: '/formularios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatrizRoute = AuthenticatedMatrizRouteImport.update({
  id: '/matriz',
  path: '/matriz',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanoDeAcaoRoute =
  AuthenticatedPlanoDeAcaoRouteImport.update({
    id: '/plano-de-acao',
    path: '/plano-de-acao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanoDeMarketingRoute =
  AuthenticatedPlanoDeMarketingRouteImport.update({
    id: '/plano-de-marketing',
    path: '/plano-de-marketing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DTokenRoute = DTokenRouteImport.update({
  id: '/d/$token',
  path: '/d/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientesRoute,
} as any)
const AuthenticatedDiagnosticosIdRoute =
  AuthenticatedDiagnosticosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDiagnosticosRoute,
  } as any)
const AuthenticatedPlanoDeMarketingClientIdRoute =
  AuthenticatedPlanoDeMarketingClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => AuthenticatedPlanoDeMarketingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnosticos': typeof AuthenticatedDiagnosticosRouteWithChildren
  '/formularios': typeof AuthenticatedFormulariosRoute
  '/matriz': typeof AuthenticatedMatrizRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/plano-de-acao': typeof AuthenticatedPlanoDeAcaoRoute
  '/plano-de-marketing': typeof AuthenticatedPlanoDeMarketingRouteWithChildren
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/d/$token': typeof DTokenRoute
  '/r/$token': typeof RTokenRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/diagnosticos/$id': typeof AuthenticatedDiagnosticosIdRoute
  '/plano-de-marketing/$clientId': typeof AuthenticatedPlanoDeMarketingClientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnosticos': typeof AuthenticatedDiagnosticosRouteWithChildren
  '/formularios': typeof AuthenticatedFormulariosRoute
  '/matriz': typeof AuthenticatedMatrizRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/plano-de-acao': typeof AuthenticatedPlanoDeAcaoRoute
  '/plano-de-marketing': typeof AuthenticatedPlanoDeMarketingRouteWithChildren
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/d/$token': typeof DTokenRoute
  '/r/$token': typeof RTokenRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/diagnosticos/$id': typeof AuthenticatedDiagnosticosIdRoute
  '/plano-de-marketing/$clientId': typeof AuthenticatedPlanoDeMarketingClientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagnosticos': typeof AuthenticatedDiagnosticosRouteWithChildren
  '/_authenticated/formularios': typeof AuthenticatedFormulariosRoute
  '/_authenticated/matriz': typeof AuthenticatedMatrizRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/plano-de-acao': typeof AuthenticatedPlanoDeAcaoRoute
  '/_authenticated/plano-de-marketing': typeof AuthenticatedPlanoDeMarketingRouteWithChildren
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/d/$token': typeof DTokenRoute
  '/r/$token': typeof RTokenRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/diagnosticos/$id': typeof AuthenticatedDiagnosticosIdRoute
  '/_authenticated/plano-de-marketing/$clientId': typeof AuthenticatedPlanoDeMarketingClientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/redefinir-senha'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/diagnosticos'
    | '/formularios'
    | '/matriz'
    | '/performance'
    | '/plano-de-acao'
    | '/plano-de-marketing'
    | '/relatorios'
    | '/d/$token'
    | '/r/$token'
    | '/clientes/$id'
    | '/diagnosticos/$id'
    | '/plano-de-marketing/$clientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/redefinir-senha'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/diagnosticos'
    | '/formularios'
    | '/matriz'
    | '/performance'
    | '/plano-de-acao'
    | '/plano-de-marketing'
    | '/relatorios'
    | '/d/$token'
    | '/r/$token'
    | '/clientes/$id'
    | '/diagnosticos/$id'
    | '/plano-de-marketing/$clientId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/redefinir-senha'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagnosticos'
    | '/_authenticated/formularios'
    | '/_authenticated/matriz'
    | '/_authenticated/performance'
    | '/_authenticated/plano-de-acao'
    | '/_authenticated/plano-de-marketing'
    | '/_authenticated/relatorios'
    | '/d/$token'
    | '/r/$token'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/diagnosticos/$id'
    | '/_authenticated/plano-de-marketing/$clientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  DTokenRoute: typeof DTokenRoute
  RTokenRoute: typeof RTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnosticos': {
      id: '/_authenticated/diagnosticos'
      path: '/diagnosticos'
      fullPath: '/diagnosticos'
      preLoaderRoute: typeof AuthenticatedDiagnosticosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formularios': {
      id: '/_authenticated/formularios'
      path: '/formularios'
      fullPath: '/formularios'
      preLoaderRoute: typeof AuthenticatedFormulariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matriz': {
      id: '/_authenticated/matriz'
      path: '/matriz'
      fullPath: '/matriz'
      preLoaderRoute: typeof AuthenticatedMatrizRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plano-de-acao': {
      id: '/_authenticated/plano-de-acao'
      path: '/plano-de-acao'
      fullPath: '/plano-de-acao'
      preLoaderRoute: typeof AuthenticatedPlanoDeAcaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plano-de-marketing': {
      id: '/_authenticated/plano-de-marketing'
      path: '/plano-de-marketing'
      fullPath: '/plano-de-marketing'
      preLoaderRoute: typeof AuthenticatedPlanoDeMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/d/$token': {
      id: '/d/$token'
      path: '/d/$token'
      fullPath: '/d/$token'
      preLoaderRoute: typeof DTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/_authenticated/diagnosticos/$id': {
      id: '/_authenticated/diagnosticos/$id'
      path: '/$id'
      fullPath: '/diagnosticos/$id'
      preLoaderRoute: typeof AuthenticatedDiagnosticosIdRouteImport
      parentRoute: typeof AuthenticatedDiagnosticosRoute
    }
    '/_authenticated/plano-de-marketing/$clientId': {
      id: '/_authenticated/plano-de-marketing/$clientId'
      path: '/$clientId'
      fullPath: '/plano-de-marketing/$clientId'
      preLoaderRoute: typeof AuthenticatedPlanoDeMarketingClientIdRouteImport
      parentRoute: typeof AuthenticatedPlanoDeMarketingRoute
    }
  }
}

interface AuthenticatedClientesRouteChildren {
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
}

const AuthenticatedClientesRouteChildren: AuthenticatedClientesRouteChildren = {
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
}

const AuthenticatedClientesRouteWithChildren =
  AuthenticatedClientesRoute._addFileChildren(
    AuthenticatedClientesRouteChildren,
  )

interface AuthenticatedDiagnosticosRouteChildren {
  AuthenticatedDiagnosticosIdRoute: typeof AuthenticatedDiagnosticosIdRoute
}

const AuthenticatedDiagnosticosRouteChildren: AuthenticatedDiagnosticosRouteChildren =
  {
    AuthenticatedDiagnosticosIdRoute: AuthenticatedDiagnosticosIdRoute,
  }

const AuthenticatedDiagnosticosRouteWithChildren =
  AuthenticatedDiagnosticosRoute._addFileChildren(
    AuthenticatedDiagnosticosRouteChildren,
  )

interface AuthenticatedPlanoDeMarketingRouteChildren {
  AuthenticatedPlanoDeMarketingClientIdRoute: typeof AuthenticatedPlanoDeMarketingClientIdRoute
}

const AuthenticatedPlanoDeMarketingRouteChildren: AuthenticatedPlanoDeMarketingRouteChildren =
  {
    AuthenticatedPlanoDeMarketingClientIdRoute:
      AuthenticatedPlanoDeMarketingClientIdRoute,
  }

const AuthenticatedPlanoDeMarketingRouteWithChildren =
  AuthenticatedPlanoDeMarketingRoute._addFileChildren(
    AuthenticatedPlanoDeMarketingRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRouteWithChildren
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiagnosticosRoute: typeof AuthenticatedDiagnosticosRouteWithChildren
  AuthenticatedFormulariosRoute: typeof AuthenticatedFormulariosRoute
  AuthenticatedMatrizRoute: typeof AuthenticatedMatrizRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedPlanoDeAcaoRoute: typeof AuthenticatedPlanoDeAcaoRoute
  AuthenticatedPlanoDeMarketingRoute: typeof AuthenticatedPlanoDeMarketingRouteWithChildren
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRouteWithChildren,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiagnosticosRoute: AuthenticatedDiagnosticosRouteWithChildren,
  AuthenticatedFormulariosRoute: AuthenticatedFormulariosRoute,
  AuthenticatedMatrizRoute: AuthenticatedMatrizRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedPlanoDeAcaoRoute: AuthenticatedPlanoDeAcaoRoute,
  AuthenticatedPlanoDeMarketingRoute:
    AuthenticatedPlanoDeMarketingRouteWithChildren,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  DTokenRoute: DTokenRoute,
  RTokenRoute: RTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
